name: frontend_flutter
description: RotaBus - Aplicativo de Transporte Público

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  dio: ^5.3.2
  flutter_launcher_icons: ^0.14.4
  http: ^1.4.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/icon/
    - lib/componentes/

# ========================================
# CONFIGURAÇÃO COMPLETA DO ÍCONE DO APP
# ========================================

flutter_icons:
  # Plataformas
  android: true
  ios: true
  
  # Ícone principal (deve ser 1024x1024 ou pelo menos 512x512)
  image_path: "assets/icon/icon.png"
  
  # Android - Ícone adaptativo (API 26+)
  adaptive_icon_background: "#FFFFFF"  # Fundo branco
  adaptive_icon_foreground: "assets/icon/icon.png"
  
  # Configurações específicas Android
  android_min_sdk_android: 21
  
  # Configurações específicas iOS
  ios_remove_alpha: true
  
  # Tamanhos específicos para garantir qualidade
  android_gravity: "fill"
  ios_content_mode: "scaleAspectFill"
